name: NexPay WorkFlow CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x,20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - name: Install frontend dependencies
      run: cd frontend && npm install
    - name: Build frontend
      run: cd frontend && npm run android
    - name: Install backend dependencies
      run: cd backend && npm install
    - name: Start backend
      run: cd backend && npm start
